### ISSUE TITLE
SearchView not colored

### ISSUE THREAD

**Issue by Heromine** [lapism/SearchView#39] opened 2016-02-22 17:23 UTC
![screenshot_2016-02-22-18-20-53](https://cloud.githubusercontent.com/assets/7427881/13226518/12ec4608-d992-11e5-8568-15ebb8d68998.png)

With all the styles settings, theme and so on...the searchview is ever white like the text and all the things of it.
I don't understand what is wrong in my styles app i have not got anything that could edit it...can you help me understanding?

**Comment by lapism** [comment] 2016-02-22 18:46
Interesting. But I think version 2.1 is not on bintray yet. Try this version after it will be released and give me a feedback. I am waiting for bintray response right now

**Comment by lapism** [comment] 2016-02-23 11:40
I will fix everything ASAP:

**Closed** 2016-02-23 17:41 UTC

**Comment by Heromine** [comment] 2016-02-23 19:46
It is not fixed

**Comment by lapism** [comment] 2016-02-23 19:59
It must be in your project, in three apps it is working great.

**Comment by lapism** [comment] 2016-02-23 20:16
Code abowe gives this >

![screenshot_20160223-211119](https://cloud.githubusercontent.com/assets/8614327/13265327/a798f900-da72-11e5-8a4a-524636d67e0c.png)

**Comment by Heromine** [comment] 2016-02-23 20:18
can you specify me the "app" xlmns?

**Comment by lapism** [comment] 2016-02-23 20:20
xmlns:app="http://schemas.android.com/apk/res-auto"

**Comment by lapism** [comment] 2016-02-23 20:20
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns:tools="http://schemas.android.com/tools"

all three important

**Comment by Heromine** [comment] 2016-02-23 20:23
Yea now it works! Sorry for the time lost

**Comment by lapism** [comment] 2016-02-23 20:24
it is OK :)

**Comment by Heromine** [comment] 2016-02-23 20:34
another problem lol...now the problem is that even with the toolbar version i got the menu one

**Comment by lapism** [comment] 2016-02-23 20:44
app:search_version = "toolbar"
app:search_style = "toolbar_classic"

it changes arrow to hamburger and back after edittext is focused

**Comment by Heromine** [comment] 2016-02-23 20:46
i am exactly using what you gave me and i obtein this
![screenshot_2016-02-23-21-46-27](https://cloud.githubusercontent.com/assets/7427881/13266151/f319a8d0-da76-11e5-99f2-d5252c15a7d7.png)

**Comment by lapism** [comment] 2016-02-23 20:49
Ha, it is not a bug. Check Play Store main screen, they have margins totally same. 48dp view + 8dp Top/Left/Right. Your toolbar under should have more then 56dp.

**Comment by Heromine** [comment] 2016-02-23 20:50
i am talking about that is menu and not toolbar

**Comment by lapism** [comment] 2016-02-23 20:51
and where is problem? I do not see anything

**Comment by Heromine** [comment] 2016-02-23 20:55
i have to have the toolbar version not the menu one, i write toolbar and i get the menu one...

**Comment by lapism** [comment] 2016-02-23 20:57
it is toolbar version :D. With hamburger is toolbar. With arrow only is menu item.

**Comment by Heromine** [comment] 2016-02-23 21:10
oh ok, i get a bit confused
